package gui;

import com.ucreativa.Gestor;
import repo.Repo.GestorRepo;

/**
 * Esta es la clase que implementa el formulario para registrar una puja a un bien subastado.
 * 
 * @author Gabriel Ruiz
 * @author Raul Espinoza
 * @author Francisco Cambronero
 */
public class frmPuja extends javax.swing.JFrame {

    Gestor gestor = GestorRepo.getGestor();

    public frmPuja() {
        initComponents();
        
        lblUsuario.setText(gestor.getNombreCompletoUsuario());
        lblBien.setText(gestor.propiedadID);
        txaBien.setText(gestor.getDescripcionPropiedadPorID(gestor.propiedadID));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblBien = new javax.swing.JLabel();
        chkAcuerdosFirmados = new javax.swing.JCheckBox();
        chkAsistenciaColaborador = new javax.swing.JCheckBox();
        chkSennialDeTrato = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtMontoSennialDeTrato = new javax.swing.JTextField();
        cmdRegistrarPuja = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaBien = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblUsuario.setText("Usuario.getNombre()");

        lblBien.setText("Bien.Id");

        chkAcuerdosFirmados.setText("Aceptar acuerdos");

        chkAsistenciaColaborador.setText("Ha recibido asistencia de un colaborador");

        chkSennialDeTrato.setText("Sennial de trato depositada");

        jLabel2.setText("Monto sennial de trato:");

        txtMontoSennialDeTrato.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMontoSennialDeTrato.setText("0.0");

        cmdRegistrarPuja.setText("Registrar puja");
        cmdRegistrarPuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarPujaActionPerformed(evt);
            }
        });

        txaBien.setColumns(20);
        txaBien.setLineWrap(true);
        txaBien.setRows(5);
        jScrollPane1.setViewportView(txaBien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAcuerdosFirmados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSennialDeTrato)
                            .addComponent(chkAsistenciaColaborador)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontoSennialDeTrato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(cmdRegistrarPuja))
                            .addComponent(lblUsuario)
                            .addComponent(lblBien, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkAcuerdosFirmados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkAsistenciaColaborador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkSennialDeTrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMontoSennialDeTrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(cmdRegistrarPuja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRegistrarPujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarPujaActionPerformed
        gestor.registrarPuja(gestor.getUsuarioId(), gestor.propiedadID, chkAcuerdosFirmados.isSelected(), chkAsistenciaColaborador.isSelected(), chkSennialDeTrato.isSelected(), Double.valueOf(txtMontoSennialDeTrato.getText()));
        this.dispose();
    }//GEN-LAST:event_cmdRegistrarPujaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPuja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPuja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAcuerdosFirmados;
    private javax.swing.JCheckBox chkAsistenciaColaborador;
    private javax.swing.JCheckBox chkSennialDeTrato;
    private javax.swing.JToggleButton cmdRegistrarPuja;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBien;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextArea txaBien;
    private javax.swing.JTextField txtMontoSennialDeTrato;
    // End of variables declaration//GEN-END:variables
}
